-- Database Schema for newjurnalku (Supabase / PostgreSQL)

-- 1. Profiles (linked to auth.users)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  nip TEXT,
  name TEXT,
  pangkat_gol TEXT,
  jabatan TEXT,
  unit_kerja TEXT,
  subject TEXT,
  role TEXT DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 2. Report Categories
CREATE TABLE public.report_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  rhk_label TEXT NOT NULL,
  is_teaching BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.report_categories ENABLE ROW LEVEL SECURITY;

-- 3. Implementation Bases
CREATE TABLE public.implementation_bases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.implementation_bases ENABLE ROW LEVEL SECURITY;

-- 4. Class Rooms
CREATE TABLE public.class_rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.class_rooms ENABLE ROW LEVEL SECURITY;

-- 5. Activities
CREATE TABLE public.activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  category_id BIGINT REFERENCES public.report_categories(id) NOT NULL,
  activity_date DATE NOT NULL DEFAULT CURRENT_DATE,
  implementation_basis_id BIGINT REFERENCES public.implementation_bases(id),
  description TEXT NOT NULL,
  output_result TEXT,
  evidence_link TEXT,
  period_start INTEGER,
  period_end INTEGER,
  topic TEXT,
  student_outcome TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

-- 6. Activity Class Rooms (Pivot)
CREATE TABLE public.activity_class_rooms (
  activity_id BIGINT REFERENCES public.activities(id) ON DELETE CASCADE,
  class_room_id BIGINT REFERENCES public.class_rooms(id) ON DELETE CASCADE,
  PRIMARY KEY (activity_id, class_room_id)
);

ALTER TABLE public.activity_class_rooms ENABLE ROW LEVEL SECURITY;

-- 7. School Settings
CREATE TABLE public.school_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_name TEXT NOT NULL,
  school_address TEXT,
  headmaster_name TEXT,
  headmaster_nip TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.school_settings ENABLE ROW LEVEL SECURITY;

-- 8. Holidays (Hari Libur)
CREATE TABLE public.holidays (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  holiday_date DATE NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  is_national BOOLEAN DEFAULT TRUE,
  created_by UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.holidays ENABLE ROW LEVEL SECURITY;

-- RLS Policies (Basic examples)
CREATE POLICY "Users can view their own profile." ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Public categories are viewable by everyone." ON public.report_categories FOR SELECT USING (true);
CREATE POLICY "Public bases are viewable by everyone." ON public.implementation_bases FOR SELECT USING (true);
CREATE POLICY "Public classes are viewable by everyone." ON public.class_rooms FOR SELECT USING (true);
CREATE POLICY "Users can view their own activities." ON public.activities FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own activities." ON public.activities FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own activities." ON public.activities FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own activities." ON public.activities FOR DELETE USING (auth.uid() = user_id);
CREATE POLICY "Holidays are viewable by everyone." ON public.holidays FOR SELECT USING (true);
CREATE POLICY "Only admins can insert holidays." ON public.holidays FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'super_admin'))
);
CREATE POLICY "Only admins can update holidays." ON public.holidays FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'super_admin'))
);
CREATE POLICY "Only admins can delete holidays." ON public.holidays FOR DELETE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'super_admin'))
);
